### ISSUE TITLE
`interface` needs syntax highlighting

### ISSUE THREAD

**Issue by fosskers** [kadena-io/pact-mode#6]
![2019-07-10-100157_958x1078_scrot](https://user-images.githubusercontent.com/229679/60989024-ca885700-a2f9-11e9-9363-e39beba4c736.png)

And potentially others. What other keywords have been added recently?

**Comment by emilypi** [comment]
Thanks - yes we definitely need it! We should be highlighting the following:

- `def`*
- `if`
- `implements`/interface
- `module/use`
- `list`
- `step/step-with-rollback`
- `bless`
